module.exports = {
	Female01: 'https://i.imgur.com/8ghakTY.png',
	Female02: 'https://i.imgur.com/jOqVgkY.png',
	Female03: 'https://i.imgur.com/ODcANYf.png',
	Female04: 'https://i.imgur.com/zBcExoN.png',
	Female05: 'https://i.imgur.com/yPcwR7K.png',
	Female06: 'https://i.imgur.com/wXbbzl7.png',
	Female07: 'https://i.imgur.com/LkMw25a.png',
	Female08: 'https://i.imgur.com/Qy1xqnA.png',
	Female09: 'https://i.imgur.com/UQ5T5PO.png',
	Female10: 'https://i.imgur.com/HU6bWvU.png',
	Female11: 'https://i.imgur.com/Jed6gwA.png',
	Female12: 'https://i.imgur.com/QJ16Ruo.png',
	Female13: 'https://i.imgur.com/kUNinbi.png',
	Female14: 'https://i.imgur.com/5DSK29g.png',
	Female15: 'https://i.imgur.com/hcbwEj0.png',
	
	Male01: 'https://i.imgur.com/zH0UoTf.png',
	Male02: 'https://i.imgur.com/8JH3992.png',
	Male03: 'https://i.imgur.com/tE7koAR.png',
	Male04: 'https://i.imgur.com/rMgWuJA.png',
	Male05: 'https://i.imgur.com/xVLJr2V.png',
	Male06: 'https://i.imgur.com/snW3iYe.png',
	Male07: 'https://i.imgur.com/gM1dDEC.png',
	Male08: 'https://i.imgur.com/U9RVp52.png',
	Male09: 'https://i.imgur.com/GyTDHYq.png',
	Male10: 'https://i.imgur.com/ZhKA4bK.png',
	Male11: 'https://i.imgur.com/tBQGtVv.png',
	Male12: 'https://i.imgur.com/J5IZoCE.png',
	Male13: 'https://i.imgur.com/uXQlpUC.png',
	Male14: 'https://i.imgur.com/o6oxbpR.png',
	Male15: 'https://i.imgur.com/ZUdrkG8.png',
};